### ISSUE TITLE
Plugin not working in Rider 2022.2 (Windows 10)

### ISSUE THREAD

**Issue by qt-xoxo** [ReallyLiri/no-namespace-providers-rider-plugin#2]
Rider firing an error on project startup. The Solution Explorer window does not render, only the "loading..." prompt is displayed (infinitely). I have tried different versions from 1.3 to the latest 1.8, none of them work properly. Although versions before 1.5 rendered a Solution Explorer window, but there was no plugin button. This may be due to some changes in Rider 2022.

![image](https://github.com/ReallyLiri/no-namespace-providers-rider-plugin/assets/104229164/44807dcd-1b61-4f96-9389-18a9ac8f0024)

![image](https://github.com/ReallyLiri/no-namespace-providers-rider-plugin/assets/104229164/80c85db1-ec7b-4b4b-8110-a58f638b4ea0)

The button appears but does nothing.

stacktrace.txt:
```
java.lang.IncompatibleClassChangeError: Found interface com.jetbrains.rider.projectView.workspace.ProjectModelEntity, but class was expected
	at com.reallyliri.plugins.namespaceproviders.NamespaceProviderSetterListener.getChildren(NamespaceProviderSetterListener.java:75)
	at com.jetbrains.rider.projectView.views.solutionExplorer.nodes.SolutionExplorerModelNode.calculateChildren(SolutionExplorerModelNode.kt:83)
	at com.jetbrains.rider.projectView.views.SolutionViewNode.getChildren(SolutionViewNode.kt:30)
	at com.jetbrains.rider.projectView.views.impl.SolutionViewTreeModel.getChildren(SolutionViewTreeModel.kt:35)
	at com.intellij.ui.tree.BaseTreeModel.getChildCount(BaseTreeModel.java:17)
	at com.intellij.ui.tree.BaseTreeModel.isLeaf(BaseTreeModel.java:12)
	at com.intellij.ui.tree.LeafState.get(LeafState.java:64)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.load(AsyncTreeModel.java:574)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:547)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:440)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:406)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:314)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:203)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:181)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:481)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by ReallyLiri** [comment]
Hi, published new version `1.9`, can you please try it?

**Comment by chpoops** [comment]
Did you publish the new version on the plugin marketplace, or here on Github?

**Comment by ReallyLiri** [comment]
sorry I was premature to comment, the plugin is still pending Jetbrains' auto approval process

**Comment by qt-xoxo** [comment]
Hello! Sorry for the late response. I don’t quite understand how it works, but the plugin supports the Rider build version from at least 233.11930, although only 233.11555 is currently available on the site, and only in an early version. Maybe I don't understand something here?

![image](https://github.com/ReallyLiri/no-namespace-providers-rider-plugin/assets/104229164/0b21d659-6105-4247-bd8c-2e8945ca67fd)
![image](https://github.com/ReallyLiri/no-namespace-providers-rider-plugin/assets/104229164/1fc0ffc8-90ae-4a8a-a90c-02921afdb03f)

**Comment by ReallyLiri** [comment]
Yes sorry I probably built the project with too new of an sdk version, checking for 2022 compatibility

**Comment by imurashka** [comment]
Hello! Is there is any chance for update this plugin to support latest rider?

**Comment by ReallyLiri** [comment]
Hi, I'm very sorry for the late response. The fix wasn't trivial due to breaking changes on JB side..
I updated the plugin to support latest Rider version, however I didn't have time to verify the functionality works, beyond build compatibility.
New version will be out in a day or two, when JetBrains approves it. If you could please check if the plugin works and report and on any problems, it will be much appreciated.

**Comment by EricBatlle** [comment]
Hey, trying in Rider 2024.3.3, receiving the following error:

```
java.lang.IncompatibleClassChangeError: Found interface com.jetbrains.rider.projectView.workspace.ProjectModelEntity, but class was expected
	at com.reallyliri.plugins.namespaceproviders.NamespaceProviderSetterListener.getChildren(NamespaceProviderSetterListener.java:75)
	at com.jetbrains.rider.projectView.views.solutionExplorer.nodes.SolutionExplorerModelNode.calculateChildren(SolutionExplorerModelNode.kt:83)
	at com.jetbrains.rider.projectView.views.SolutionViewNode.getChildren(SolutionViewNode.kt:24)
	at com.jetbrains.rider.projectView.views.impl.SolutionViewTreeModel.getChildren(SolutionViewTreeModel.kt:35)
	at com.intellij.ui.tree.BaseTreeModel.getChildCount(BaseTreeModel.java:17)
	at com.intellij.ui.tree.BaseTreeModel.isLeaf(BaseTreeModel.java:12)
	at com.intellij.ui.tree.LeafState.get(LeafState.java:62)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.load(AsyncTreeModel.java:700)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.load(AsyncTreeModel.java:679)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.computeNode(AsyncTreeModel.java:668)
	at com.intellij.ui.tree.AsyncTreeModel$Command.computeNode(AsyncTreeModel.java:541)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:361)
	at com.intellij.util.concurrency.CoroutineInvokerDelegate.run(CoroutineInvokerDelegate.kt:38)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:189)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:173)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:470)
	at com.intellij.util.concurrency.CoroutineInvokerDelegate.offer$lambda$2(CoroutineInvokerDelegate.kt:27)
	at com.intellij.util.concurrency.SequentialBgtCoroutineInvokerDelegate$doLaunch$1.invokeSuspend$lambda$1$lambda$0(CoroutineInvokerDelegate.kt:97)
	at com.intellij.util.concurrency.BgtCoroutineInvokerDelegate.withProperContext$lambda$0(CoroutineInvokerDelegate.kt:73)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:114)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$4(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2$lambda$1(cancellableReadAction.kt:32)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2(cancellableReadAction.kt:30)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:28)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:103)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:87)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invokeSuspend(InternalReadAction.kt:53)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:49)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:62)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:29)
	at com.intellij.util.concurrency.BgtCoroutineInvokerDelegate.withProperContext(CoroutineInvokerDelegate.kt:72)
	at com.intellij.util.concurrency.SequentialBgtCoroutineInvokerDelegate$doLaunch$1.invokeSuspend(CoroutineInvokerDelegate.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

```
